### ISSUE TITLE
[Crash] Unrecoverable error in factorio 0.17.18

### ISSUE THREAD

**Issue by jarquafelmu** [eduran84/LTN_Tracker#19] opened 2019-03-26 13:24 UTC
**Error message or bug description**
```
Error MainLoop.cpp:1142: Exception at tick 33860198: The mod LTN - Logistic Train Network caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LogisticTrainNetwork::on_tick (ID 0)
The mod LTN Tracker caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Tracker::Custom event (ID 268)
The mod LTN Tracker caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Tracker::Custom event (ID 271)
real number expected got nil.
stack traceback:
	__LTN_Tracker__/ui/classes/GuiComposition.lua:158: in function 'get'
	__LTN_Tracker__/ui/classes/GuiComposition.lua:172: in function 'get_el'
	__LTN_Tracker__/ui/outer_frame.lua:109: in function 'set_alert'
	__LTN_Tracker__/ltnt/gui_ctrl.lua:219: in function <__LTN_Tracker__/ltnt/gui_ctrl.lua:215>
	[C]: in function 'raise_event'
	__LTN_Tracker__/ltnt/data_processing.lua:505: in function <__LTN_Tracker__/ltnt/data_processing.lua:492>
stack traceback:
	[C]: in function 'raise_event'
	__LTN_Tracker__/ui/classes/GuiComposition.lua:158: in function 'get'
	__LTN_Tracker__/ui/classes/GuiComposition.lua:172: in function 'get_el'
	__LTN_Tracker__/ui/outer_frame.lua:109: in function 'set_alert'
	__LTN_Tracker__/ltnt/gui_ctrl.lua:219: in function <__LTN_Tracker__/ltnt/gui_ctrl.lua:215>
	[C]: in function 'raise_event'
	__LTN_Tracker__/ltnt/data_processing.lua:505: in function <__LTN_Tracker__/ltnt/data_processing.lua:492>
stack traceback:
	__LTN_Tracker__/ltnt/data_processing.lua:505: in function <__LTN_Tracker__/ltnt/data_processing.lua:492>
stack traceback:
	[C]: in function 'raise_event'
	__LTN_Tracker__/ltnt/data_processing.lua:505: in function <__LTN_Tracker__/ltnt/data_processing.lua:492>
stack traceback:
	__LogisticTrainNetwork__/script/dispatcher.lua:87: in function <__LogisticTrainNetwork__/script/dispatcher.lua:34>
stack traceback:
	[C]: in function 'raise_event'
	__LogisticTrainNetwork__/script/dispatcher.lua:87: in function <__LogisticTrainNetwork__/script/dispatcher.lua:34
5829.989 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod LTN - Logistic Train Network caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LogisticTrainNetwork::on_tick (ID 0)
The mod LTN Tracker caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Tracker::Custom event (ID 268)
The mod LTN Tracker caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Tracker::Custom event (ID 271)
real number expected got nil.
stack traceback:
	__LTN_Tracker__/ui/classes/GuiComposition.lua:158: in function 'get'
	__LTN_Tracker__/ui/classes/GuiComposition.lua:172: in function 'get_el'
	__LTN_Tracker__/ui/outer_frame.lua:109: in function 'set_alert'
	__LTN_Tracker__/ltnt/gui_ctrl.lua:219: in function <__LTN_Tracker__/ltnt/gui_ctrl.lua:215>
	[C]: in function 'raise_event'
	__LTN_Tracker__/ltnt/data_processing.lua:505: in function <__LTN_Tracker__/ltnt/data_processing.lua:492>
stack traceback:
	[C]: in function 'raise_event'
	__LTN_Tracker__/ui/classes/GuiComposition.lua:158: in function 'get'
	__LTN_Tracker__/ui/classes/GuiComposition.lua:172: in function 'get_el'
	__LTN_Tracker__/ui/outer_frame.lua:109: in function 'set_alert'
	__LTN_Tracker__/ltnt/gui_ctrl.lua:219: in function <__LTN_Tracker__/ltnt/gui_ctrl.lua:215>
	[C]: in function 'raise_event'
	__LTN_Tracker__/ltnt/data_processing.lua:505: in function <__LTN_Tracker__/ltnt/data_processing.lua:492>
stack traceback:
	__LTN_Tracker__/ltnt/data_processing.lua:505: in function <__LTN_Tracker__/ltnt/data_processing.lua:492>
stack traceback:
	[C]: in function 'raise_event'
	__LTN_Tracker__/ltnt/data_processing.lua:505: in function <__LTN_Tracker__/ltnt/data_processing.lua:492>
stack traceback:
	__LogisticTrainNetwork__/script/dispatcher.lua:87: in function <__LogisticTrainNetwork__/script/dispatcher.lua:34>
stack traceback:
	[C]: in function 'raise_event'
	__LogisticTrainNetwork__/script/dispatcher.lua:87: in function <__LogisticTrainNetwork__/script/dispatcher.lua:34>
```

**To Reproduce**
Removed a min or max train length restriction from an active LTN station.

**LTN version**
1.10.4

**LTN Tracker version**
0.9.6

**Factorio version**
0.17.18

**Log file**
[factorio-previous.log](https://github.com/Yousei9/Logistic-Train-Network/files/3006186/factorio-previous.log)

**Comment by jarquafelmu** [comment] 2019-03-26 13:25
I had posted it here (https://github.com/Yousei9/Logistic-Train-Network/issues/161) but was told that this bug was caused by LTN Tracker.

**Comment by eduran84** [comment] 2019-03-26 14:50
Thanks for the report. This bug is indeed caused by LTN Tracker. Do you happen to have a save game from around the time when that bug occurred? Because I can't figure out how this error could possibly happen.

**Comment by jarquafelmu** [comment] 2019-03-26 21:57
Yeah i can get you a save game

**Comment by jarquafelmu** [comment] 2019-03-26 21:59
It could be related to the GUI crashes that were addressed in patches *.19 - *.21

**Comment by jarquafelmu** [comment] 2019-03-26 22:51
I was about to say that the issue had been resolved in 0.17.21. But as I starting writing this the crash happened again. I think it was due to a schedule being created.

**Error:**
```
Error MainLoop.cpp:1142: Exception at tick 33860198: The mod LTN - Logistic Train Network caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LogisticTrainNetwork::on_tick (ID 0)
The mod LTN Tracker caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Tracker::Custom event (ID 268)
The mod LTN Tracker caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Tracker::Custom event (ID 271)
__LTN_Tracker__/ui/classes/GuiComposition.lua:175: attempt to index local 'element' (a nil value)
stack traceback:
	__LTN_Tracker__/ui/classes/GuiComposition.lua:175: in function 'get_el'
	__LTN_Tracker__/ui/outer_frame.lua:109: in function 'set_alert'
	__LTN_Tracker__/ltnt/gui_ctrl.lua:219: in function <__LTN_Tracker__/ltnt/gui_ctrl.lua:215>
	[C]: in function 'raise_event'
	__LTN_Tracker__/ltnt/data_processing.lua:505: in function <__LTN_Tracker__/ltnt/data_processing.lua:492>
stack traceback:
	__LTN_Tracker__/ltnt/data_processing.lua:505: in function <__LTN_Tracker__/ltnt/data_processing.lua:492>
stack traceback:
	[C]: in function 'raise_event'
	__LTN_Tracker__/ltnt/data_processing.lua:505: in function <__LTN_Tracker__/ltnt/data_processing.lua:492>
stack traceback:
	__LogisticTrainNetwork__/script/dispatcher.lua:87: in function <__LogisticTrainNetwork__/script/dispatcher.lua:34>
stack traceback:
	[C]: in function 'raise_event'
	__LogisticTrainNetwork__/script/dispatcher.lua:87: in function <__LogisticTrainNetwork__/script/dispatcher.lua:34
 101.203 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod LTN - Logistic Train Network caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LogisticTrainNetwork::on_tick (ID 0)
The mod LTN Tracker caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Tracker::Custom event (ID 268)
The mod LTN Tracker caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Tracker::Custom event (ID 271)
__LTN_Tracker__/ui/classes/GuiComposition.lua:175: attempt to index local 'element' (a nil value)
stack traceback:
	__LTN_Tracker__/ui/classes/GuiComposition.lua:175: in function 'get_el'
	__LTN_Tracker__/ui/outer_frame.lua:109: in function 'set_alert'
	__LTN_Tracker__/ltnt/gui_ctrl.lua:219: in function <__LTN_Tracker__/ltnt/gui_ctrl.lua:215>
	[C]: in function 'raise_event'
	__LTN_Tracker__/ltnt/data_processing.lua:505: in function <__LTN_Tracker__/ltnt/data_processing.lua:492>
stack traceback:
	__LTN_Tracker__/ltnt/data_processing.lua:505: in function <__LTN_Tracker__/ltnt/data_processing.lua:492>
stack traceback:
	[C]: in function 'raise_event'
	__LTN_Tracker__/ltnt/data_processing.lua:505: in function <__LTN_Tracker__/ltnt/data_processing.lua:492>
stack traceback:
	__LogisticTrainNetwork__/script/dispatcher.lua:87: in function <__LogisticTrainNetwork__/script/dispatcher.lua:34>
stack traceback:
	[C]: in function 'raise_event'
	__LogisticTrainNetwork__/script/dispatcher.lua:87: in function <__LogisticTrainNetwork__/script/dispatcher.lua:34>
```
**Log:**
[factorio-current.log](https://github.com/eduran84/LTN_Tracker/files/3010767/factorio-current.log)

**Save:**
https://drive.google.com/open?id=1fOQXjAevzt-KasOFoufR_AnQgJwHiII_

**Comment by eduran84** [comment] 2019-03-27 11:11
Thanks! Will be fixed with 0.9.7.
That was yet another case of UI mods messing with LTNT's UI.

**Closed** 2019-03-27 19:04 UTC
Labels: bug

**Comment by jarquafelmu** [comment] 2019-03-28 00:54
I'm curious which UI mod was it that was interfering?

**Comment by eduran84** [comment] 2019-03-28 08:06
So am I, but the way things work its very hard to figure out. All I can say is that in your save parts of the LTNT UI had been deleted in a way I did not anticipate. That only happens to become a problem when trying to access them. By that time, there is no way for me to know which mod interfered.

I think there are a few mods around that (accidentally or because their authors don't know better) delete one of the root GUI elements to which LTNT is attached. Since every mod runs in its own lua instance, that might seem like a save thing to do. However, UI elements are shared across all mods and can therefore be accessed by any mod.
